services:
  - type: web
    name: jurisprudentie-render
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python flask_server.py"
    envVars:
      - key: PORT
        value: 8080
